### model
model_name_or_path: llms/Llama-3.1-8B-Instruct
trust_remote_code: true
### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: anzhen_cot_train,tongji_cot_train,gulou_cot_train
template: llama3
cutoff_len: 8000
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/IECV_renji_cot_train/llama3-8b/lora/sft_15ep
logging_steps: 10
save_steps: 30
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000

## eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 30
# llamafactory-cli train ./examples/train_lora/IECV_renji_llama3_8B.yaml
